"""add structured agent output columns to tasks

Revision ID: 16f1d4f48cec
Revises: 954bbb41cbb2
Create Date: 2026-07-14 03:15:43.116892

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16f1d4f48cec'
down_revision: Union[str, Sequence[str], None] = '954bbb41cbb2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('plan', sa.Text(), nullable=True))
    op.add_column('tasks', sa.Column('research_notes', sa.Text(), nullable=True))
    op.add_column('tasks', sa.Column('generated_code', sa.Text(), nullable=True))
    op.add_column('tasks', sa.Column('review_notes', sa.Text(), nullable=True))
    op.add_column('tasks', sa.Column('test_results', sa.Text(), nullable=True))
    op.add_column('tasks', sa.Column('documentation', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'documentation')
    op.drop_column('tasks', 'test_results')
    op.drop_column('tasks', 'review_notes')
    op.drop_column('tasks', 'generated_code')
    op.drop_column('tasks', 'research_notes')
    op.drop_column('tasks', 'plan')
    # ### end Alembic commands ###
